name: flutter_learn_app
description: Flutter Learn App for Mobile Computing Lab
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.1
  youtube_player_iframe: ^5.0.0  # Web-compatible YouTube player
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  flutter_markdown: ^0.7.3 # This is i added for content material
  animate_do: ^3.1.2
  fl_chart: ^0.68.0
  intl: ^0.19.0




dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/content/
    - assets/images/